MVCPersona/Models/Empleado.cs
using System.ComponentModel.DataAnnotations;

namespace MVCPersona.Models
{
    public class Empleado
    {

        public int ID { get; set; }

        [StringLength(100)]
        [Required(ErrorMessage = "El nombre del empleado es requerido")]
        [Display(Name = "Nombre del Empleado")]
        public string NombreEmpleado { get; set; }

        [StringLength(100)]
        [Required(ErrorMessage = "El apellido del empleado es requerido")]
        [Display(Name = "Apellido del Empleado")]
        public string ApellidoEmpleado { get; set; }

        [Required(ErrorMessage = "La fecha de contratación es requerida")]
        [Display(Name = "Fecha de Contratación")]
        [DataType(DataType.Date)]
        public DateTime FechaContratacion { get; set; }

        [StringLength(100)]
        [Required(ErrorMessage = "El puesto del empleado es requerido")]
        [Display(Name = "Puesto del Empleado")]
        public string PuestoEmpleado { get; set; }

        public ICollection<Asignacion> Asignaciones { get; set; }
    }
}

MVCPersona/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCPersona.Models;

namespace MVCPersona.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly PersonaDBContext _context;

        public EmpleadosController(PersonaDBContext context)
        {
            _context = context;
        }

        // GET: Empleados
        public async Task<IActionResult> Index(String textoABuscar)
        {

            if(_context.Empleados == null)
            {
                return Problem("No se ha inicializado el contexto");
            }
            var empleados = from e in _context.Empleados
                            select e;
            if(!String.IsNullOrEmpty(textoABuscar))
            {
                empleados = empleados.Where(e => e.NombreEmpleado.Contains(textoABuscar));
            }

            return View(await empleados.ToListAsync());
           // return View(await _context.Empleados.ToListAsync());
        }

        [HttpPost]
        public string Index(string textoABuscar, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + textoABuscar;
        }

        // GET: Empleados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .FirstOrDefaultAsync(m => m.ID == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleados/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empleados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,NombreEmpleado,ApellidoEmpleado,FechaContratacion,PuestoEmpleado")] Empleado empleado)
        {
            ModelState.Remove("Asignaciones");
            if (ModelState.IsValid)
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleados/Edit/5
        public async Task<IActionResult> Edit(int? id)
         {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,NombreEmpleado,ApellidoEmpleado,FechaContratacion,PuestoEmpleado")] Empleado empleado)
        {
            ModelState.Remove("Asignaciones");
            if (id != empleado.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleados/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .FirstOrDefaultAsync(m => m.ID == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado != null)
            {
                _context.Empleados.Remove(empleado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
            return _context.Empleados.Any(e => e.ID == id);
        }
    }
}

MVCPersona/Views/Empleados/Create.cshtml
@model MVCPersona.Models.Empleado

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreEmpleado" class="control-label"></label>
                <input asp-for="NombreEmpleado" class="form-control" />
                <span asp-validation-for="NombreEmpleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoEmpleado" class="control-label"></label>
                <input asp-for="ApellidoEmpleado" class="form-control" />
                <span asp-validation-for="ApellidoEmpleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaContratacion" class="control-label"></label>
                <input asp-for="FechaContratacion" class="form-control" />
                <span asp-validation-for="FechaContratacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PuestoEmpleado" class="control-label"></label>
                <input asp-for="PuestoEmpleado" class="form-control" />
                <span asp-validation-for="PuestoEmpleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCPersona/Views/Empleados/Delete.cshtml
@model MVCPersona.Models.Empleado

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaContratacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaContratacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PuestoEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PuestoEmpleado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCPersona/Views/Empleados/Details.cshtml
@model MVCPersona.Models.Empleado

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaContratacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaContratacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PuestoEmpleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PuestoEmpleado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Editar</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCPersona/Views/Empleados/Edit.cshtml
@model MVCPersona.Models.Empleado

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="NombreEmpleado" class="control-label"></label>
                <input asp-for="NombreEmpleado" class="form-control" />
                <span asp-validation-for="NombreEmpleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoEmpleado" class="control-label"></label>
                <input asp-for="ApellidoEmpleado" class="form-control" />
                <span asp-validation-for="ApellidoEmpleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaContratacion" class="control-label"></label>
                <input asp-for="FechaContratacion" class="form-control" />
                <span asp-validation-for="FechaContratacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PuestoEmpleado" class="control-label"></label>
                <input asp-for="PuestoEmpleado" class="form-control" />
                <span asp-validation-for="PuestoEmpleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCPersona/Views/Empleados/Index.cshtml
@model IEnumerable<MVCPersona.Models.Empleado>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Crear Empleado</a>
</p>

<form asp-controller="Empleados" asp-action="Index" method="get">
    <p>
        Nombre Empleado : <input type="text" name="textoABuscar" class="form-control"/>
        <input type="submit" value="Filtrar" class="btn btn-info"/>
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreEmpleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoEmpleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaContratacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PuestoEmpleado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaContratacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PuestoEmpleado)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>