MVCPersona/Models/Proyecto.cs
using System.ComponentModel.DataAnnotations;

namespace MVCPersona.Models
{
    public class Proyecto
    {

        public int ID { get; set; }

        [StringLength(200)]
        [Required(ErrorMessage = "El nombre del proyecto es requerido")]
        [Display(Name = "Nombre del Proyecto")]
        public string NombreProyecto { get; set; }

        [StringLength(300)]
        [Required(ErrorMessage = "La descripción del proyecto es requerida")]
        [Display(Name = "Descripción del Proyecto")]
        public string DescripcionProyecto { get; set; }

        [Required(ErrorMessage = "La fecha del proyecto es requerida")]
        [DataType(DataType.Date)]   
        [Display(Name = "Fecha de incio del Proyecto")]
        public DateTime FechaInicio { get; set; }

        public ICollection<Asignacion> Asignaciones { get; set; }
    }
}

MVCPersona/Controllers/ProyectosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCPersona.Models;

namespace MVCPersona.Controllers
{
    public class ProyectosController : Controller
    {
        private readonly PersonaDBContext _context;

        public ProyectosController(PersonaDBContext context)
        {
            _context = context;
        }

        // GET: Proyectos
        public async Task<IActionResult> Index(String textoABuscar)
        {
            if (_context.Proyectos == null)
            {
                return Problem("No se ha inicializado el contexto");
            }
            var proyectos = from p in _context.Proyectos
                            select p;
            if (!String.IsNullOrEmpty(textoABuscar))
            {
                proyectos = proyectos.Where(p => p.NombreProyecto.Contains(textoABuscar));
            }

            return View(await proyectos.ToListAsync());
        }
        [HttpPost]
        public string Index(string textoABuscar, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + textoABuscar;
        }
        // GET: Proyectos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyecto = await _context.Proyectos
                .FirstOrDefaultAsync(m => m.ID == id);
            if (proyecto == null)
            {
                return NotFound();
            }

            return View(proyecto);
        }

        // GET: Proyectos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proyectos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,NombreProyecto,DescripcionProyecto,FechaInicio")] Proyecto proyecto)
        {
            ModelState.Remove("Asignaciones");
            if (ModelState.IsValid)
            {
                _context.Add(proyecto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proyecto);
        }

        // GET: Proyectos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyecto = await _context.Proyectos.FindAsync(id);
            if (proyecto == null)
            {
                return NotFound();
            }
            return View(proyecto);
        }

        // POST: Proyectos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,NombreProyecto,DescripcionProyecto,FechaInicio")] Proyecto proyecto)
        {
            ModelState.Remove("Asignaciones");
            if (id != proyecto.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proyecto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProyectoExists(proyecto.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proyecto);
        }

        // GET: Proyectos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyecto = await _context.Proyectos
                .FirstOrDefaultAsync(m => m.ID == id);
            if (proyecto == null)
            {
                return NotFound();
            }

            return View(proyecto);
        }

        // POST: Proyectos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proyecto = await _context.Proyectos.FindAsync(id);
            if (proyecto != null)
            {
                _context.Proyectos.Remove(proyecto);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProyectoExists(int id)
        {
            return _context.Proyectos.Any(e => e.ID == id);
        }
    }
}

MVCPersona/Views/Proyectos/Create.cshtml
@model MVCPersona.Models.Proyecto

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Proyecto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreProyecto" class="control-label"></label>
                <input asp-for="NombreProyecto" class="form-control" />
                <span asp-validation-for="NombreProyecto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionProyecto" class="control-label"></label>
                <input asp-for="DescripcionProyecto" class="form-control" />
                <span asp-validation-for="DescripcionProyecto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCPersona/Views/Proyectos/Delete.cshtml
@model MVCPersona.Models.Proyecto

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreProyecto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreProyecto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescripcionProyecto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescripcionProyecto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCPersona/Views/Proyectos/Details.cshtml
@model MVCPersona.Models.Proyecto

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreProyecto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreProyecto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescripcionProyecto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescripcionProyecto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Editar</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCPersona/Views/Proyectos/Edit.cshtml
@model MVCPersona.Models.Proyecto

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Proyecto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="NombreProyecto" class="control-label"></label>
                <input asp-for="NombreProyecto" class="form-control" />
                <span asp-validation-for="NombreProyecto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionProyecto" class="control-label"></label>
                <input asp-for="DescripcionProyecto" class="form-control" />
                <span asp-validation-for="DescripcionProyecto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInicio" class="control-label"></label>
                <input asp-for="FechaInicio" class="form-control" />
                <span asp-validation-for="FechaInicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCPersona/Views/Proyectos/Index.cshtml
@model IEnumerable<MVCPersona.Models.Proyecto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Crear Proyecto</a>
</p>
<form asp-controller="Proyectos" asp-action="Index" method="get">
    <p>
        Nombre del Proyecto : <input type="text" name="textoABuscar" class="form-control" />
        <input type="submit" value="Filtrar" class="btn btn-info" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreProyecto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescripcionProyecto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInicio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreProyecto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescripcionProyecto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicio)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>