MVCPersona/Controllers/AsignacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCPersona.Models;

namespace MVCPersona.Controllers
{
    public class AsignacionesController : Controller
    {
        private readonly PersonaDBContext _context;

        public AsignacionesController(PersonaDBContext context)
        {
            _context = context;
        }

        // GET: Asignaciones
        public async Task<IActionResult> Index(String textoABuscar)
        {
            if (_context.Asignaciones == null)
            {
                return Problem("No se ha inicializado el contexto");
            }
            var asignaciones = from a in _context.Asignaciones.Include(a => a.Empleado).Include(a => a.Proyecto)
            select a;
            if (!String.IsNullOrEmpty(textoABuscar))
            {
                asignaciones = asignaciones.Where(a => a.Empleado.NombreEmpleado.Contains(textoABuscar));
            }

            return View(await asignaciones.ToListAsync());
            //var personaDBContext = _context.Asignaciones.Include(a => a.Empleado).Include(a => a.Proyecto);
            //return View(await personaDBContext.ToListAsync());
        }
        [HttpPost]
        public string Index(string textoABuscar, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + textoABuscar;
        }

        // GET: Asignaciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asignacion = await _context.Asignaciones
                .Include(a => a.Empleado)
                .Include(a => a.Proyecto)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (asignacion == null)
            {
                return NotFound();
            }

            return View(asignacion);
        }

        // GET: Asignaciones/Create
        public IActionResult Create()
        {
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "ID", "NombreEmpleado");
            ViewData["ProyectoId"] = new SelectList(_context.Proyectos, "ID", "DescripcionProyecto");
            return View();
        }

        // POST: Asignaciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FechaAsignacion,RolAsignacion,EmpleadoId,ProyectoId")] Asignacion asignacion)
        {
            ModelState.Remove("Empleado");
            ModelState.Remove("Proyecto");

            if (ModelState.IsValid)
            {
                _context.Add(asignacion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "ID", "ApellidoEmpleado", asignacion.EmpleadoId);
            ViewData["ProyectoId"] = new SelectList(_context.Proyectos, "ID", "DescripcionProyecto", asignacion.ProyectoId);
            return View(asignacion);
        }

        // GET: Asignaciones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asignacion = await _context.Asignaciones.FindAsync(id);
            if (asignacion == null)
            {
                return NotFound();
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "ID", "ApellidoEmpleado", asignacion.EmpleadoId);
            ViewData["ProyectoId"] = new SelectList(_context.Proyectos, "ID", "DescripcionProyecto", asignacion.ProyectoId);
            return View(asignacion);
        }

        // POST: Asignaciones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FechaAsignacion,RolAsignacion,EmpleadoId,ProyectoId")] Asignacion asignacion)
        {
            ModelState.Remove("Empleado");
            ModelState.Remove("Proyecto");
            if (id != asignacion.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(asignacion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AsignacionExists(asignacion.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "ID", "ApellidoEmpleado", asignacion.EmpleadoId);
            ViewData["ProyectoId"] = new SelectList(_context.Proyectos, "ID", "DescripcionProyecto", asignacion.ProyectoId);
            return View(asignacion);
        }

        // GET: Asignaciones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asignacion = await _context.Asignaciones
                .Include(a => a.Empleado)
                .Include(a => a.Proyecto)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (asignacion == null)
            {
                return NotFound();
            }

            return View(asignacion);
        }

        // POST: Asignaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var asignacion = await _context.Asignaciones.FindAsync(id);
            if (asignacion != null)
            {
                _context.Asignaciones.Remove(asignacion);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AsignacionExists(int id)
        {
            return _context.Asignaciones.Any(e => e.ID == id);
        }
    }
}

MVCPersona/Views/Asignaciones/Create.cshtml
@model MVCPersona.Models.Asignacion

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Asignacion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaAsignacion" class="control-label"></label>
                <input asp-for="FechaAsignacion" class="form-control" />
                <span asp-validation-for="FechaAsignacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RolAsignacion" class="control-label"></label>
                <input asp-for="RolAsignacion" class="form-control" />
                <span asp-validation-for="RolAsignacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpleadoId" class="control-label"></label>
                <select asp-for="EmpleadoId" class ="form-control" asp-items="ViewBag.EmpleadoId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProyectoId" class="control-label"></label>
                <select asp-for="ProyectoId" class ="form-control" asp-items="ViewBag.ProyectoId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCPersona/Views/Asignaciones/Delete.cshtml
@model MVCPersona.Models.Asignacion

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Asignacion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAsignacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAsignacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RolAsignacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RolAsignacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empleado.ApellidoEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proyecto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proyecto.DescripcionProyecto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCPersona/Views/Asignaciones/Details.cshtml
@model MVCPersona.Models.Asignacion

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Asignacion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaAsignacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaAsignacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RolAsignacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RolAsignacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empleado.ApellidoEmpleado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Proyecto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Proyecto.DescripcionProyecto)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Editar</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCPersona/Views/Asignaciones/Edit.cshtml
@model MVCPersona.Models.Asignacion

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Asignacion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FechaAsignacion" class="control-label"></label>
                <input asp-for="FechaAsignacion" class="form-control" />
                <span asp-validation-for="FechaAsignacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RolAsignacion" class="control-label"></label>
                <input asp-for="RolAsignacion" class="form-control" />
                <span asp-validation-for="RolAsignacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmpleadoId" class="control-label"></label>
                <select asp-for="EmpleadoId" class="form-control" asp-items="ViewBag.EmpleadoId"></select>
                <span asp-validation-for="EmpleadoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProyectoId" class="control-label"></label>
                <select asp-for="ProyectoId" class="form-control" asp-items="ViewBag.ProyectoId"></select>
                <span asp-validation-for="ProyectoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCPersona/Views/Asignaciones/Index.cshtml
@model IEnumerable<MVCPersona.Models.Asignacion>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Crear Asignación</a>
</p>
<form asp-controller="Asignaciones" asp-action="Index" method="get">
    <p>
        Nombre Empleado en asignación : <input type="text" name="textoABuscar" class="form-control" />
        <input type="submit" value="Filtrar" class="btn btn-info" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FechaAsignacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RolAsignacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Empleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Proyecto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FechaAsignacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RolAsignacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empleado.NombreEmpleado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Proyecto.DescripcionProyecto)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>